### ISSUE TITLE
Cannot pass arguments to main

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/fletch#113] opened 2015-08-26 13:19 UTC
Take the following code (in the file `args.dart`):

```
main(List<String> args) => print(args);
```

Compile and run with no arguments:

```
out/DebugIA32/fletch compile-and-run args.dart
Starting session. Type 'help' for a list of commands.

> r
[]
### process terminated
```

Compile and run _with_ arguments:

```
out/DebugIA32/fletch compile-and-run args.dart 1 2 3
Unknown option: '1'
```

Compile it to a snapshot:

```
out/DebugIA32/fletch args.dart compile-and-run --out args.snapshot
```

Run with no arguments:

```
out/DebugIA32/fletch-vm args.snapshot
[]
```

Run _with_ arguments:

```
out/DebugIA32/fletch-vm args.snapshot 1 2 3
ERROR: Cannot open 3
Waiting for compiler on 127.0.0.1:40380
```

**Comment by skabet** [comment] 2015-09-02 12:28
Duplicate of issue 18.

**Closed by skabet** 2015-09-02 12:28 UTC
