### ISSUE TITLE
Fletch driver could use a compile-in-fresh-compiler command

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/fletch#105] opened 2015-08-20 09:47 UTC
For developing on the fletchc compiler it is frustrating to have to kill the fletch resident compiler before running a new compilation.

There could also be a seperate fletchc entrypoint.

**Comment by madsager** [comment] 2015-08-20 10:03
There was, it was removed.

fletch shutdown is your friend. Easy to script.

**Comment by madsager** [comment] 2015-08-20 10:08
Sorry, didn't mean to close the issue; reopened.

Instead of a separate entry point, maybe we can add a convenience script to the repo for the compiler devs if this is slowing you down?

**Comment by sigurdm** [comment] 2015-08-20 10:41
I had not seen the shutdown command. That makes it easier.
I would not say that it slows me down now that I have my own script - but it will slow down anyone else who has to discover it.

**Comment by sigurdm** [comment] 2015-08-20 10:43
What is the difference between `fletch shutdown` and `tools/persistent_process_info.sh -kill` (if any)?

**Comment by peter-ahe-google** [comment] 2015-09-07 07:50
Duplicate of issue #122. The proposed solution is to create a test that is easy to run from the command line as well.

**Closed by peter-ahe-google** 2015-09-07 07:50 UTC
Labels: Tools
