### ISSUE TITLE
Trying to compiling a file that does not exist results in a 'RangeError'

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/fletch#253] opened 2015-10-21 20:50 UTC
See output below. The message

```Error: Error reading '/Users/sgjesse/Downloads/fletch-sdk/samples/raspberry_pi/sense_hat/xxx.dart' (No such file or directory)```

is fine, but the `RangeError` following it is confusing.

```
$ ../../../bin/fletch run xxx.dart in session remote
/Users/sgjesse/Downloads/fletch-sdk/samples/raspberry_pi/sense_hat/xxx.dart:
Error: Error reading '/Users/sgjesse/Downloads/fletch-sdk/samples/raspberry_pi/sense_hat/xxx.dart' (No such file or directory)
Compile error
RangeError (index): Invalid value: Not in range 0..4, inclusive: -1
#0      List.[] (dart:core-patch/array.dart:11)
#1      StackTrace.visibleFrame (package:fletchc/stack_trace.dart:160:23)
#2      StackTrace.list (package:fletchc/stack_trace.dart:168:12)
#3      DebugState.list (package:fletchc/debug_state.dart:135:30)
#4      Session.list.<list_async_body> (package:fletchc/session.dart:551:23)
#5      _rootRunUnary (dart:async/zone.dart:911)
#6      _CustomZone.runUnary (dart:async/zone.dart:811)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#9      _Future._completeWithValue (dart:async/future_impl.dart:368)
#10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#11     _rootRun (dart:async/zone.dart:904)
#12     _CustomZone.run (dart:async/zone.dart:803)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:736)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#15     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by peter-ahe-google** [comment] 2015-10-21 21:55
Thanks for reporting! Dupe of #241.

**Closed by peter-ahe-google** 2015-10-21 21:55 UTC
Labels: Compiler
