### ISSUE TITLE
Timers can leak ports

### ISSUE THREAD

**Issue by skabet** [dart-lang/fletch#280] opened 2015-11-04 15:09 UTC
In non-crashing programs, there is a chance we don't correctly clear scheduled timers/ports from the eventhandler.

It may be related to callbacks throwing errors, but probably not exclusively.

**Comment by madsager** [comment] 2015-11-04 17:50
Is this a duplicate of: https://github.com/dart-lang/fletch/issues/57

If not, can we add a bit more context to understand the difference? :)

**Comment by skabet** [comment] 2015-11-04 17:55
It's not. See https://codereview.chromium.org/1417553009/ for a fix of the
issue (I did not have more context at the point of creating the issue,
except validating there was an issue with timers).

**Comment by madsager** [comment] 2015-11-04 17:57
Ah, cool. That was nice and simple. :) Thanks Anders!

**Closed** 2015-11-05 09:13 UTC
